version = 0.1
[default.deploy.parameters]
stack_name = "nestjs-api-dev"
resolve_s3 = true
s3_prefix = "nestjs-api-dev"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBSecretArn=\"arn:aws:secretsmanager:us-west-2:174508894736:secret:prod/aurora/db-app-7byiIF\""
image_repositories = []
